= Anti-Makarot Act
:toc:

[.text-center]
_From RandomFan#3511 Rainychville Law Services_


== Full text

[.text-center]
[discrete]
==== Rainychville Government

[.text-center]
[discrete]
=== Anti-Makarot Act

[.text-center]
*AN ACT* to mitigae the effects of Makarot's continued posting of religious material, sometimes racist or discriminatory on the Rainychville Discord.

[.text-center]
*Law code*: _ECIR 12.1.355.10_

***


=== SEC 1. SHORT TITLE.
. This act may be cited as the Anti-Makarot Act.

=== SEC 2. DEFINITIONS.
Makarot:: as a member of the Rainychville Discord server.

=== SEC 3. EXCEPTIONS.
. To the extent permitted by this law, all denominations of Islam shall be exempted from this Act.

=== SEC 4. POSTING OF RELIGIOUS CONTENT.
. The posting of religious content by Makarot shall be tracked, logged, and Moderation Actions taken if necessary. Religions covered include but are not limited to:
["arabic"]
    .. all variants/denominations of Christianity; and
    .. new religious movements, which may be commonly referred to as "cults".
. Religious buildings within the districts of Rainychville with the highest presence of Makarot shall be demolished, and their land replaced with public government buildings, except where the religious building is of historic, practical, or non-religious cultural significance to the residents of the Rainychville Discord.

=== SEC 5. CALENDARS.
. The usage of BC/AD notation, where AD is the shortened form of "anno domini", which is Medieval Latin for "in the year of the lord"footnote:[The word "lord" in religious contexts is intentionally lower-cased in this
    document.] shall be replaced with alternate notations that do not make any reference to religion, such as BCE/CE notation (Before Common Era and Common Era respectively), where this removal of BC/AD notation shall occur on:
["arabic"]
    .. physical calendars or inscriptions on Rainychville Government buildings, except where such inscription is of historic, practical or non-religious cultural significance,
    .. clocks/date counters on Rainychville Government websites;
    .. any form of content that displays a date,
  except where:
    .. the content is a video that contains a date, where either BC/AD notation has been omitted or where the date's formatting does not imply any reference to religion;
    .. the content cannot be easily altered; or
    .. the content has been archived.
. Calendars produced by the Rainychville Government shall not have any religious symbol affixed on them in any shape, form, material, or method.

=== SEC 6. TAXATION.
. No sentient lifeform shall be entitled to tax deductions or a reduction in tax rate for any donation made to a religious organization.

=== SEC 7. BANS.
. Makarot shall not be permitted to enter Rainychville under any circumstances.

