= Rainychville Crocodile Protection Act
:toc:
:sectnums: |,all|


AN ACT to preserve the Rainychville crocodile, and prevent
the poaching, abuse, and exploitation of said
crocodiles by sentient lifeforms (excluding the crocodile's
natural prey) or organizations.

== SHORT TITLE.
. This act may be cited as the Rainychville Crocodile Protection Act.

== DEFINITIONS.
. Rainychville crocodile means any instance of a crocodile which is of
a species endemic to Rainychville.

== RAINYCHVILLE WILDLIFE SERVICE.
. The Rainychville Wildlife Service shall be formed and granted
jurisdiction over nature reserves in Rainychville territory.
. The RWS shall have, within reason:
["arabic"]
.. the authority to detain any sentient lifeform that can be
reasonably suspected of or determined to have engaged in the
act of abusing, poaching, or exploiting a Rainychville
crocodile; and
.. the authority to humanely restrain or terminate a
Rainychville crocodile if such action is necessary for the
crocodile's wellbeing.
. The RWS, where it's jurisdiction overlaps with similar organizations
of the Rainychville Government, shall collaborate with aforementioned
similar organizations to perform their collective duties.
. The RWS shall consist of:
["arabic"]
.. the Rainychville Park Police (RPP), which shall have the authority
to make arrests in national parks; and
.. the RWS Internet Division (RWSID), which shall:
["arabic"]
... publish information educating and informing people on the nature of
Rainychville crocodiles, so as to prevent the poaching, abuse, or
infliction of harm or pain by any sentient lifeform towards a
Rainychville Crocodile; and
... publish advertisements to persuade people to visit Rainychville
national parks, while keeping a safe distance from Rainychville crocodiles;
... and for the representation of the RWS on the internet; and
.. the Rainychville Park Rangers, which shall oversee the maintenance of
national parks; and
.. the Rainychville Wildlife Veterinarian Service (RWVS), which shall
oversee the medical care of Rainychville crocodiles and wildlife under the
jurisdiction of the RWS; and
.. other parts of the Rainychville Wildlife Service, which may be formed at
the discretion of the Service.

== CONSERVATION MEASURES.
. No structure shall be built that impedes the movement, migration, or
locomotion of the Rainychville crocodile including but not limited to
walls, fences, watchtowers, except where the structure is:
["arabic"]
.. intended to protect the Rainychville crocodile from harm caused by human
beings, machines; except where the harm is caused by:
["arabic"]
... disease, where:
["arabic"]
.... it cannot be prevented at reasonable or practical cost
or benefit to the crocodile, humanity, the Rainychville Government,
+++<del>+++it's natural prey+++</del>+++, +++<del>+++ or God+++</del>+++;
... natural events;
... +++<del>+++acts of God+++</del>+++;
... attacks or hostility from it's natural predators; or
.. intended to prevent the Rainychville crocodile from harming any human being
or destroying property.
. No Rainychville crocodile shall be poached or it's body parts used as a
souvenir, medicine, or sold, except where the collection process of such body
part does not cause significant pain to the crocodile.
. Tracking devices may only be implemented on specific instances of
Rainychville crocodiles if the implantation of such a tracking device is
important, beneficial, or critical to a scientific study,
. After a person is supplied with sufficient documentation, in writing or
digitally, regarding traps or mechanisms, which the Rainychville Government
is able to determine within reason that such mechanism or trap is being used to
hunt, kill, harm, hold captive, capture, where the intention of such capture
is to keep the crocodile as a pet, or to sell it, or to damage a Rainychville
crocodile physically, the Rainychville Government shall:
["arabic"]
.. have the authority to:
["arabic"]
... dismantle, disable, destroy, or dispose of the
trap; and
... issue orders against the person to cease and desist from the continued
manufacture, deployment, or preparation of such trap;
.. where:
["arabic"]
... with the disposal of the trap, parties involved in it's preparation,
["arabic"]
.... no compensation of any form is granted for the trap's loss or the
cost incurred by the disposal of the trap.

***

ECIR 12.1.355.11
