= Rainychville Crocodile Protection Act
:toc:
:sectnums: |,all|


AN ACT to preserve the Rainychville crocodile, and prevent
the poaching, abuse, and exploitation of said
crocodiles by sentient lifeforms (excluding the crocodile's
natural prey) or organizations.

== SHORT TITLE.
. This act may be cited as the Rainychville Crocodile Protection Act.

== DEFINITIONS.
. Rainychville crocodile means any instance of a crocodile which is of
a species endemic to Rainychville.

== RAINYCHVILLE WILDLIFE SERVICE.
. The Rainychville Wildlife Service shall be formed and granted
jurisdiction over nature reserves in Rainychville territory.
. The RWS shall have, within reason:
["arabic"]
.. the authority to detain any sentient lifeform that can be
reasonably suspected of or determined to have engaged in the
act of abusing, poaching, or exploiting a Rainychville
crocodile; and
.. the authority to humanely restrain or terminate a
Rainychville crocodile if such action is necessary for the
crocodile's wellbeing.
. The RWS, where it's jurisdiction overlaps with similar organizations
of the Rainychville Government, shall collaborate with aforementioned
similar organizations to perform their collective duties.
. The RWS shall consist of:
["arabic"]
.. the Rainychville Park Police (RPP), which shall have the authority
to make arrests in national parks; and
.. the RWS Internet Division (RWSID), which shall:
["arabic"]
... publish information educating and informing people on the nature of
Rainychville crocodiles, so as to prevent the poaching, abuse, or
infliction of harm or pain by any sentient lifeform towards a
Rainychville Crocodile; and
... publish advertisements to persuade people to visit Rainychville
national parks, while keeping a safe distance from Rainychville crocodiles;
... and for the representation of the RWS on the internet; and
.. the Rainychville Park Rangers, which shall oversee the maintenance of
national parks; and
.. the Rainychville Wildlife Veterinarian Service (RWVS), which shall
oversee the medical care of Rainychville crocodiles and wildlife under the
jurisdiction of the RWS.


***

ECIR 12.1.355.11
